# DO NOT EDIT! Auto-generated via carmel install.
package Carmel::MySetup;

our %environment = (
  'inc' => [
    '/root/.carmel/5.40.1-x86_64-linux/builds/Config-Tiny-2.30/blib/lib',
    '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib'
  ],
  'path' => [
    '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/script'
  ],
  'execs' => {
    'Mojolicious' => {
      'hypnotoad' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/script/hypnotoad',
      'mojo' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/script/mojo',
      'morbo' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/script/morbo'
    }
  },
  'base' => '/workspaces/Mojolicious',
  'modules' => {
    'Config/Tiny.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Config-Tiny-2.30/blib/lib/Config/Tiny.pm',
    'Mojo.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojo.pm',
    'Mojo/Asset.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojo/Asset.pm',
    'Mojo/Asset/File.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojo/Asset/File.pm',
    'Mojo/Asset/Memory.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojo/Asset/Memory.pm',
    'Mojo/Base.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojo/Base.pm',
    'Mojo/BaseUtil.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojo/BaseUtil.pm',
    'Mojo/ByteStream.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojo/ByteStream.pm',
    'Mojo/Cache.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojo/Cache.pm',
    'Mojo/Collection.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojo/Collection.pm',
    'Mojo/Content.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojo/Content.pm',
    'Mojo/Content/MultiPart.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojo/Content/MultiPart.pm',
    'Mojo/Content/Single.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojo/Content/Single.pm',
    'Mojo/Cookie.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojo/Cookie.pm',
    'Mojo/Cookie/Request.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojo/Cookie/Request.pm',
    'Mojo/Cookie/Response.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojo/Cookie/Response.pm',
    'Mojo/DOM.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojo/DOM.pm',
    'Mojo/DOM/CSS.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojo/DOM/CSS.pm',
    'Mojo/DOM/HTML.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojo/DOM/HTML.pm',
    'Mojo/Date.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojo/Date.pm',
    'Mojo/DynamicMethods.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojo/DynamicMethods.pm',
    'Mojo/EventEmitter.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojo/EventEmitter.pm',
    'Mojo/Exception.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojo/Exception.pm',
    'Mojo/File.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojo/File.pm',
    'Mojo/Headers.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojo/Headers.pm',
    'Mojo/HelloWorld.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojo/HelloWorld.pm',
    'Mojo/Home.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojo/Home.pm',
    'Mojo/IOLoop.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojo/IOLoop.pm',
    'Mojo/IOLoop/Client.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojo/IOLoop/Client.pm',
    'Mojo/IOLoop/Server.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojo/IOLoop/Server.pm',
    'Mojo/IOLoop/Stream.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojo/IOLoop/Stream.pm',
    'Mojo/IOLoop/Subprocess.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojo/IOLoop/Subprocess.pm',
    'Mojo/IOLoop/TLS.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojo/IOLoop/TLS.pm',
    'Mojo/JSON.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojo/JSON.pm',
    'Mojo/JSON/Pointer.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojo/JSON/Pointer.pm',
    'Mojo/Loader.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojo/Loader.pm',
    'Mojo/Log.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojo/Log.pm',
    'Mojo/Message.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojo/Message.pm',
    'Mojo/Message/Request.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojo/Message/Request.pm',
    'Mojo/Message/Response.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojo/Message/Response.pm',
    'Mojo/Parameters.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojo/Parameters.pm',
    'Mojo/Path.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojo/Path.pm',
    'Mojo/Promise.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojo/Promise.pm',
    'Mojo/Reactor.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojo/Reactor.pm',
    'Mojo/Reactor/EV.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojo/Reactor/EV.pm',
    'Mojo/Reactor/Poll.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojo/Reactor/Poll.pm',
    'Mojo/Server.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojo/Server.pm',
    'Mojo/Server/CGI.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojo/Server/CGI.pm',
    'Mojo/Server/Daemon.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojo/Server/Daemon.pm',
    'Mojo/Server/Hypnotoad.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojo/Server/Hypnotoad.pm',
    'Mojo/Server/Morbo.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojo/Server/Morbo.pm',
    'Mojo/Server/Morbo/Backend.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojo/Server/Morbo/Backend.pm',
    'Mojo/Server/Morbo/Backend/Poll.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojo/Server/Morbo/Backend/Poll.pm',
    'Mojo/Server/PSGI.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojo/Server/PSGI.pm',
    'Mojo/Server/Prefork.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojo/Server/Prefork.pm',
    'Mojo/Template.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojo/Template.pm',
    'Mojo/Transaction.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojo/Transaction.pm',
    'Mojo/Transaction/HTTP.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojo/Transaction/HTTP.pm',
    'Mojo/Transaction/WebSocket.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojo/Transaction/WebSocket.pm',
    'Mojo/URL.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojo/URL.pm',
    'Mojo/Upload.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojo/Upload.pm',
    'Mojo/UserAgent.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojo/UserAgent.pm',
    'Mojo/UserAgent/CookieJar.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojo/UserAgent/CookieJar.pm',
    'Mojo/UserAgent/Proxy.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojo/UserAgent/Proxy.pm',
    'Mojo/UserAgent/Server.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojo/UserAgent/Server.pm',
    'Mojo/UserAgent/Transactor.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojo/UserAgent/Transactor.pm',
    'Mojo/Util.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojo/Util.pm',
    'Mojo/WebSocket.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojo/WebSocket.pm',
    'Mojolicious.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojolicious.pm',
    'Mojolicious/Command.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojolicious/Command.pm',
    'Mojolicious/Command/Author/cpanify.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojolicious/Command/Author/cpanify.pm',
    'Mojolicious/Command/Author/generate.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojolicious/Command/Author/generate.pm',
    'Mojolicious/Command/Author/generate/app.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojolicious/Command/Author/generate/app.pm',
    'Mojolicious/Command/Author/generate/dockerfile.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojolicious/Command/Author/generate/dockerfile.pm',
    'Mojolicious/Command/Author/generate/lite_app.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojolicious/Command/Author/generate/lite_app.pm',
    'Mojolicious/Command/Author/generate/makefile.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojolicious/Command/Author/generate/makefile.pm',
    'Mojolicious/Command/Author/generate/plugin.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojolicious/Command/Author/generate/plugin.pm',
    'Mojolicious/Command/Author/inflate.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojolicious/Command/Author/inflate.pm',
    'Mojolicious/Command/cgi.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojolicious/Command/cgi.pm',
    'Mojolicious/Command/daemon.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojolicious/Command/daemon.pm',
    'Mojolicious/Command/eval.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojolicious/Command/eval.pm',
    'Mojolicious/Command/get.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojolicious/Command/get.pm',
    'Mojolicious/Command/prefork.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojolicious/Command/prefork.pm',
    'Mojolicious/Command/psgi.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojolicious/Command/psgi.pm',
    'Mojolicious/Command/routes.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojolicious/Command/routes.pm',
    'Mojolicious/Command/version.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojolicious/Command/version.pm',
    'Mojolicious/Commands.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojolicious/Commands.pm',
    'Mojolicious/Controller.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojolicious/Controller.pm',
    'Mojolicious/Lite.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojolicious/Lite.pm',
    'Mojolicious/Plugin.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojolicious/Plugin.pm',
    'Mojolicious/Plugin/Config.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojolicious/Plugin/Config.pm',
    'Mojolicious/Plugin/DefaultHelpers.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojolicious/Plugin/DefaultHelpers.pm',
    'Mojolicious/Plugin/EPLRenderer.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojolicious/Plugin/EPLRenderer.pm',
    'Mojolicious/Plugin/EPRenderer.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojolicious/Plugin/EPRenderer.pm',
    'Mojolicious/Plugin/HeaderCondition.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojolicious/Plugin/HeaderCondition.pm',
    'Mojolicious/Plugin/JSONConfig.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojolicious/Plugin/JSONConfig.pm',
    'Mojolicious/Plugin/Mount.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojolicious/Plugin/Mount.pm',
    'Mojolicious/Plugin/NotYAMLConfig.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojolicious/Plugin/NotYAMLConfig.pm',
    'Mojolicious/Plugin/TagHelpers.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojolicious/Plugin/TagHelpers.pm',
    'Mojolicious/Plugins.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojolicious/Plugins.pm',
    'Mojolicious/Renderer.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojolicious/Renderer.pm',
    'Mojolicious/Routes.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojolicious/Routes.pm',
    'Mojolicious/Routes/Match.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojolicious/Routes/Match.pm',
    'Mojolicious/Routes/Pattern.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojolicious/Routes/Pattern.pm',
    'Mojolicious/Routes/Route.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojolicious/Routes/Route.pm',
    'Mojolicious/Sessions.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojolicious/Sessions.pm',
    'Mojolicious/Static.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojolicious/Static.pm',
    'Mojolicious/Types.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojolicious/Types.pm',
    'Mojolicious/Validator.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojolicious/Validator.pm',
    'Mojolicious/Validator/Validation.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Mojolicious/Validator/Validation.pm',
    'Test/Mojo.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/Test/Mojo.pm',
    'ojo.pm' => '/root/.carmel/5.40.1-x86_64-linux/builds/Mojolicious-9.39/blib/lib/ojo.pm'
  },
  'prereqs' => {
    'runtime' => {
      'requires' => {
        'Config::Tiny' => '0',
        'Mojolicious' => '0'
      }
    }
  },
);

1;
